name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Rub by cypress command line
        default: npm cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1
        
      - name: Install dependencies
        run:  npm install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
