name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Rub by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-E2E-electron:
     runs-on: ubuntu-latest
     container:
      image: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
      options: --user 1001
     steps:
      - name: Get code
        uses: actions/checkout@v4.1.1
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: c106ffdd-d5a5-4fe9-950a-828dc530e847
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-E2E-chrome:
     needs: cypress-E2E-electron
     runs-on: ubuntu-latest
     container:
      image: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
      options: --user 1001
     steps:
      - name: Get code
        uses: actions/checkout@v4.1.1
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: c106ffdd-d5a5-4fe9-950a-828dc530e847
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-E2E-firefox:
     needs: cypress-E2E-electron
     runs-on: ubuntu-latest
     container:
      image: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
      options: --user 1001
     steps:
      - name: Get code
        uses: actions/checkout@v4.1.1
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: c106ffdd-d5a5-4fe9-950a-828dc530e847
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
